# playbook_tasks.yaml
---
- name: ensure ntpd is at the latest version
  apt: name=ntp state=present
  register: ntpinstalled
  notify:
  - restart ntp

- name: start ntp
  when: ntpinstalled|success
  service: name=ntp state={{STATE}}

- name: stop ntp
  when: ntpinstalled|failed
  service: name=ntp state=stopped
