# playbook_multi.yaml
---
- hosts: all
  vars:
      ntp_server: us.pool.ntp.org
  tasks:
      - include: tasks.yaml
        STATE: started

  handlers:
      - include: handlers.yaml STATE=restarted
