# playbook_tasks.yaml
---
- name: ensure ntpd is at the latest version
  apt: name=ntp state=present
  register: ntpinstalled

- template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
  - restart ntp

- name: start ntp
  when: ntpinstalled|success
  service: name=ntp state={{STATE}}
